name: Update Gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */8 * * *" # update every 8 hours
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
        run: npm install
      - name: Update gist
        uses: kylemocode/medium-stat-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEDIUM_USER_NAME: ${{ secrets.MEDIUM_USER_NAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
